#' @include utils.r
NULL

#' Read 10x contig file
#'
#' @param contig_file character. Path to contig_annotations file generated by 10x cellranger.
#' @param verbose logical. Print progress. Default is TRUE
#'
#' @importFrom data.table fread
#'
#' @return A VDJ information data.frame
#' @export
#'
#' @examples
#' contig_file = system.file('extdata', '10x_all_contig_annotations.csv.gz', package = 'TrustVDJ')
#' contig = .Read10x_contig(contig_file = contig_file)
#' head(contig)
#'
.Read10x_contig = function(contig_file, verbose = TRUE) {

  # 0. check parameter
  contig_file = as.character(contig_file %|||% NA)
  if(!file.exists(contig_file))
    stop('!!! ', timer(), ' 10x contig_annotations file does not exist: ', contig_file, ' !!!')

  # 1. read contig file
  if(verbose) cat('-->', timer(), 'reading:', contig_file, '<--\n')
  contig = data.table::fread(contig_file, data.table = FALSE)
  if(!nrow(contig))
    stop('!!! ', timer(), ' There is no content in 10x contig_annotations file !!!')

  # return
  if(verbose) cat('-->', timer(), 'done <--\n')
  contig
}

#' Read 10x consensus file
#'
#' @param consensus_file character. Path to consensus_annotations file generated by 10x cellranger.
#' @param verbose logical. Print progress. Default is TRUE
#'
#' @importFrom data.table fread
#'
#' @return A VDJ information data.frame
#' @export
#'
#' @examples
#' consensus_file = system.file('extdata', '10x_consensus_annotations.csv.gz', package = 'TrustVDJ')
#' consensus = .Read10x_consensus(consensus_file = consensus_file)
#' head(consensus)
#'
.Read10x_consensus = function(consensus_file, verbose = TRUE) {

  # 0. check parameter
  consensus_file = as.character(consensus_file %|||% NA)
  if(!file.exists(consensus_file))
    stop('!!! ', timer(), ' 10x consensus_annotations file does not exist: ', consensus_file, ' !!!')

  # 1. read consensus file
  if(verbose) cat('-->', timer(), 'reading:', consensus_file, '<--\n')
  consensus = data.table::fread(consensus_file, data.table = FALSE)
  if(!nrow(consensus))
    stop('!!! ', timer(), ' There is no content in 10x consensus_annotations file !!!')

  # return
  if(verbose) cat('-->', timer(), 'done <--\n')
  consensus
}

#' Read 10x clonotype file
#'
#' @param clonotype_file character. Path to clonotype file generated by 10x cellranger.
#' @param verbose logical. Print progress. Default is TRUE
#'
#' @importFrom data.table fread
#' @importFrom stats setNames
#'
#' @return A VDJ information data.frame
#' @export
#'
#' @examples
#' clonotype_file = system.file('extdata', '10x_clonotypes.csv.gz', package = 'TrustVDJ')
#' clonotype = .Read10x_clonotype(clonotype_file = clonotype_file)
#' head(clonotype)
#'
.Read10x_clonotype = function(clonotype_file, verbose = TRUE) {

  # 0. check parameter
  clonotype_file = as.character(clonotype_file %|||% NA)
  if(!file.exists(clonotype_file))
    stop('!!! ', timer(), ' 10x clonotypes file does not exist: ', clonotype_file, ' !!!')

  # 1. read clonotype file
  if(verbose) cat('-->', timer(), 'reading:', clonotype_file, '<--\n')
  clonotype = data.table::fread(clonotype_file, data.table = FALSE)
  if(!nrow(clonotype))
    stop('!!! ', timer(), ' There is no content in 10x clonotypes file !!!')

  # 2. process clonotype
  if(verbose) p = utils::txtProgressBar(style = 3)
  clonotype_data = do.call(rbind, lapply(seq(clonotype$clonotype_id), function(i) {
    id = clonotype$clonotype_id[i]
    cdr3nt = unlist(strsplit(clonotype$cdr3s_nt[i], ';'))
    cdr3aa = unlist(strsplit(clonotype$cdr3s_aa[i], ';'))
    # progress
    if(verbose) utils::setTxtProgressBar(p, i/length(clonotype$clonotype_id))
    # return
    stats::setNames(data.frame(id, paste0(id, '_consensus', seq(cdr3nt)) ,clonotype$frequency[i], clonotype$proportion[i],
                               cdr3nt, cdr3aa, clonotype$inkt_evidence[i], clonotype$mait_evidence[i]), consensusName)
  }))

  # return
  if(verbose) cat('-->', timer(), 'done <--\n')
  clonotype_data
}

#' Read AIRR/10x report files
#'
#' \code{Read10x} reads AIRR file and/or contig/consensus/clonotype file generated by 10x cellranger (> 6.0).
#' Generally
#' AIRR file: airr_rearrangement.tsv (from cellranger);
#' contig files: all_contig_annotations.csv, filtered_contig_annotations.csv;
#' consensus file: consensus_annotations.csv;
#' clonotype file: clonotypes.csv.
#' (.gz supported)
#' 1. AIRR + filtered_contig:
#' \code{Read10x} will read AIRR and add it 'fwr.., cdr.. and full_length' column based on filtered_contig file.
#' 2. only one file:
#' \code{Read10x} will return a data.frame for this file.
#' 3. AIRR/contig + consensus/clonotype:
#' \code{Read10x} will ignore consensus/clonotype file when either AIRR or contig file is given.
#' Note that when AIRR + all_contig, only contigs in AIRR will be return.
#' 4. consensus + clonotype (no AIRR nor contig):
#' \code{Read10x} will ignore clonotype file when consensus file is given.
#' (Don't worry about the information of inkt/mait_evidence in clonotype, these can be reproduced in downstream analysis.)
#'
#' @param airr_file character. Path to AIRR file.
#' @param contig_file character. Path to contig_annotations file generated by 10x cellranger.
#' @param consensus_file character. Path to consensus_annotations file generated by 10x cellranger.
#' @param clonotype_file character. Path to clonotypes file generated by 10x cellranger.
#' @param verbose logical. Print progress. Default is TRUE.
#'
#' @return A VDJ information data.frame
#' @export
#'
#' @examples
#' # file paths
#' airr_file      = system.file('extdata', '10x_airr_rearrangement.tsv.gz', package = 'TrustVDJ')
#' contig_file    = system.file('extdata', '10x_all_contig_annotations.csv.gz', package = 'TrustVDJ')
#' #or contig_file =
#' #system.file('extdata', '10x_filtered_contig_annotations.csv.gz', package = 'TrustVDJ')
#' consensus_file = system.file('extdata', '10x_consensus_annotations.csv.gz', package = 'TrustVDJ')
#' clonotype_file = system.file('extdata', '10x_clonotypes.csv.gz', package = 'TrustVDJ')
#'
#' # both AIRR and contig
#' \donttest{
#' data = Read10x(airr_file = airr_file, contig_file = contig_file)
#' head(data)
#' }
#'
#' # only AIRR
#' data = Read10x(airr_file = airr_file)
#' head(data)
#'
#' # only contig
#' data = Read10x(contig_file = contig_file)
#' head(data)
#'
#' # only consensus
#' data = Read10x(consensus_file = consensus_file)
#' head(data)
#'
#' # only clonotype
#' data = Read10x(clonotype_file = clonotype_file)
#' head(data)
#'
Read10x = function(airr_file      = NULL,
                   contig_file    = NULL,
                   consensus_file = NULL,
                   clonotype_file = NULL,
                   verbose        = TRUE ){

  # 1. Read AIRR file
  airr_file = as.character(airr_file %|||% NA)
  airr = if(file.exists(airr_file)) .ReadAIRR(airr_file, verbose = verbose) else
    if(verbose) cat('--!', timer(), 'Ignored AIRR report file due to no exist:', airr_file, '!--\n')

  # 2. Read contig file
  contig_file = as.character(contig_file %|||% NA)
  contig = if(file.exists(contig_file)) .Read10x_contig(contig_file, verbose = verbose) else
    if(verbose) cat('--!', timer(), 'Ignored 10x contig_annotations file due to no exist:', contig_file, '!--\n')

  # 3. If no 1.&2. file
  if(is.null(airr) && is.null(contig)) {

    # 3.1 Read consensus file
    consensus_file = as.character(consensus_file %|||% NA)
    consensus = if(file.exists(consensus_file)) .Read10x_consensus(consensus_file, verbose = verbose) else
      if(verbose) cat('--!', timer(), 'Ignored 10x consensus_annotations file due to no exist:', consensus_file, '!--\n')

    # 3.2. Read clonotype file
    if(is.null(consensus)) {
      clonotype_file = as.character(clonotype_file %|||% NA)
      clonotype = if(file.exists(clonotype_file)) .Read10x_clonotype(clonotype_file, verbose = verbose) else
        stop('!!! ', timer(), ' Even clonotype file does not exist, please check input file path !!!')
      return(clonotype)
    } else return(consensus)
  }

  # 4. Return only contig
  if(is.null(airr)) return(contig)

  # 5. Return only airr
  if(is.null(contig)) return(airr)

  # 6. contig with airr (base on contig_id)
  if(verbose) cat('-->', timer(), 'combine airr and contig info <--\n')
  contig = contig[match(airr$sequence_id, contig$contig_id, nomatch = 1),]
  if(!sum(airr$sequence_id != contig$contig_id)) {
    airr = cbind(airr, contig[grep('^fwr|^cdr1|^cdr2|^full_length', colnames(contig))])
  } else warning('--! ', timer(), ' Ignored combine: sequence_id in AIRR not equal to contig_id in contig file !--')

  # return
  airr
}

#' Read10x in groups
#'
#' @param airr_files character. Path to AIRR files.
#' @param contig_files character. Path to contig_annotations files generated by 10x cellranger.
#' @param consensus_files character. Path to consensus_annotations files generated by 10x cellranger.
#' @param clonotype_files character. Path to clonotypes files generated by 10x cellranger.
#' @param names character. Sample names. Default number index.
#' @param group list. A list named by group names and contain corresponding sample names.
#' @param clonotype_colnames character. Colnames of clonotype_id. Default \code{clonotype_id}
#' @param consensus_colnames character. Colnames of consensus_id. Default \code{consensus_id}
#' @param unique_clonotype logical. Make clonotypes unique in group. Default \code{TRUE}
#' @param unique_clonotype_by_cdr3nt logical. Unique clonotypes by same cdr3 DNA, if FALSE, by same cdr3 Amino-acid. Default \code{TRUE}
#' @param cdr3nt_colnames character. Colnames of cdr3_nt. Default \code{cdr3_nt}
#' @param cdr3aa_colnames character. Colnames of cdr3_aa. Default \code{cdr3}
#' @param verbose logical. Print progress. Default \code{TRUE}.
#'
#' @return a Trust raw data object (TrustRaw object)
#' @export
#'
#' @examples
#' print('waiting...')
#' 
Read10xs = function(airr_files = NULL, contig_files = NULL, consensus_files = NULL, clonotype_files = NULL,
                    names = NULL, group = NULL, 
                    clonotype_colnames = NULL, consensus_colnames = NULL, 
                    unique_clonotype = TRUE, unique_clonotype_by_cdr3nt = TRUE, 
                    cdr3nt_colnames = NULL, cdr3aa_colnames = NULL,
                    verbose = TRUE ){
  
  # check parameter
  nfile = max(length(airr_files), length(contig_files), length(consensus_files), length(clonotype_files))
  names = as.character(names %|||% seq(nfile))
  group = group %|||% list('Group' = names)
  outer = setdiff(unlist(group), names)
  if(length(outer))
    stop('!!! ', timer(), ' group contains not available sample names: ', paste(outer, collapse = ','), ' !!!')
  clonoNames  = as.character(clonotype_colnames %|||% 'clonotype_id') 
  conseNames  = as.character(consensus_colnames %|||% 'consensus_id')
  cdr3ntNames = as.character(cdr3nt_colnames    %|||% 'cdr3_nt')
  cdr3aaNames = as.character(cdr3aa_colnames    %|||% 'cdr3')

  # consensus #
  consenS = setNames(lapply(seq(nfile), function(i) {
    if(verbose) cat('-->', timer(), 'read sample:', names[i], '<--\n')
    consen    = Read10x(airr_file = airr_files[i], contig_file = contig_files[i],
                        consensus_file = consensus_files[i], clonotype_file = clonotype_files[i],
                        verbose = verbose)
    clonoName = clonoNames[clonoNames %in% colnames(consen)][1] %|||% NULL
    conseName = conseNames[conseNames %in% colnames(consen)][1] %|||% NULL
    if(length(clonoName)) { 
      if(verbose) cat('-->', timer(), 'checked clonotype_id colname:', clonoName, 'give sample prefix <--\n')
      consen[[clonoName]] = paste0(names[i], '_', consen[[clonoName]])
    }
    if(length(conseName)) {
      if(verbose) cat('-->', timer(), 'checked consensus_id colname:', conseName, 'give sample prefix <--\n')
      consen[[conseName]] = paste0(names[i], '_', consen[[conseName]])
    }
    consen
  }), names)
  
  # consen group
  consenG = setNames(lapply(names(group), function(n) {
    if(verbose) cat('-->', timer(), 'process samples:', paste(group[[n]], collapse = ','), 'in group:', n, '<--\n')
    consen_gp = consenS[ group[[n]] ]
    
    # clonotype id #
    clono_gp  = do.call(rbind, lapply(seq(consen_gp), function(i) {
      consen     = consen_gp[[i]]
      sample     = names(consen_gp)[i]
      clonoName  = clonoNames[clonoNames   %in% colnames(consen)][1] %|||% NULL
      if(!length(clonoName)) return()
      cdr3ntName = cdr3ntNames[cdr3ntNames %in% colnames(consen)][1] %|||% NULL
      cdr3aaName = cdr3aaNames[cdr3aaNames %in% colnames(consen)][1] %|||% NULL
      # clonotype by same cdr3nt //= cdr3aa #
      cdr3Name = if(length(cdr3ntName) & unique_clonotype_by_cdr3nt) {
        if(verbose) cat('-->', timer(), 'check clonotype by cdr3-nt in sample:', sample, '<--\n')
        cdr3ntName
      } else if(length(cdr3aaName)) {
        if(verbose) cat('--!', timer(), 'cdr3-nt not found, check clonotype by cdr3-aa in sample:', sample, '!--\n')
        cdr3aaName
      } else 
        if(verbose) cat('--!', timer(), 'cdr3-nt and cdr3-aa not found, check clonotype ignored !--\n')
      if(length(cdr3Name))
        do.call(rbind, lapply(unique(consen[[clonoName]]), function(clo)
          data.frame(sample = sample, id = clo, nt = 
            paste(sort(consen[[cdr3Name]][consen[[clonoName]] %in% clo]), collapse = ';')) ))
    }))
    
    # unique id
    dup_clono = data.frame(clono_gp[ clono_gp$nt %in% clono_gp$nt[duplicated(clono_gp$nt)], ])
    rm(clono_gp)
    if (unique_clonotype & nrow(dup_clono)) {
      if(verbose) cat('-->', timer(), 'make clonotype_id unique <--\n')
      for (nt in unique(dup_clono$nt)) {
        dup_id = dup_clono[dup_clono$nt %in% nt, -3]
        for (i in 2:nrow(dup_id)) {
          sample    = dup_id$sample[i]
          clonoName = clonoNames[clonoNames %in% colnames(consen_gp[[sample]])][1]
          conseName = conseNames[conseNames %in% colnames(consen_gp[[sample]])][1] %|||% NULL
          # dup -> replace
          d_clo  = dup_id$id[i]
          d_idx  = which(consen_gp[[sample]][[clonoName]] %in% d_clo)
          d_cons = if(length(conseName)) consen_gp[[sample]][[conseName]][d_idx]
          r_clo  = dup_id$id[1]
          r_cons = sub(d_clo, r_clo, d_cons)
          # change
          consen_gp[[sample]][[clonoName]][d_idx] = r_clo
          if(length(conseName)) consen_gp[[sample]][[conseName]][d_idx] = r_cons
        }
      }
    }
    
    # consensus
    consen_gp = do.call(rbind, consen_gp)
    rownames(consen_gp) = NULL
    consen_gp
  }), names(group))
  
  # return
  if(verbose) cat('-->', timer(), 'done <--\n')
  new('TrustRaw', samples = consenS, groups = consenG, info = group)
}

